# Generated by Django 5.0.6 on 2024-07-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('student_sem', models.IntegerField()),
                ('student_sub', models.CharField(max_length=100)),
                ('note_desc', models.TextField()),
                ('note_file', models.FileField(upload_to='submit_notes')),
            ],
        ),
    ]
